version: "3.2"
services:
 agro-producer:
  build: ./agro-producer
  ports:
   - "8080:8080"
  depends_on:
   - rabbitmq
  network_mode: "host"
 agro-consumer:
  build: ./agro-consumer
  ports:
   - "8090:8090"
  depends_on:
   - rabbitmq
  network_mode: "host"
 rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq
  restart: always
  ports:
   - 5672:5672
   - 15672:15672
  volumes: 
   - ./dados:/var/lib/rabbitmq/
  environment:
   - RABBITMQ_DEFAULT_USER=admin
   - RABBITMQ_DEFAULT_PASS=123456